= Hrvoje Nezic blog
// PSClasses
https://github.com/hnezic
:nofooter:
:psClassesArticle:
:psClassesProject: https://github.com/hnezic/PSClasses[project]

// == About this blog

=== SDEditGen: structured syntax for sdedit sequence diagrams

_SDEditGen_ is a preprocessor tool for __Quick Sequence Diagram Editor__,
better known as __sdedit__.
_QSDE / sdedit_ is an excellent open source _text to UML_ tool, but its
syntax is not
so nice: it is often unintutitive, cryptic, and hard to remember.
Also, like syntax of many sequence diagram tools, _sdedit's_ syntax is
__unstructured__. It is easy to create and read a _Hello world (Bob -> Alice)_
example, but it is much harder to write and read complex real-world diagrams.
_SDEditGen_ aims to provide a structured, nicer, easier and more
intuitive syntax for __sdedit__.
link:sdEditGen.html[Read more]

=== PSClasses: classes for PowerShell versions before 5.0

The _PSClasses_ project provides classes with inheritance to PowerShell 
versions earlier than 5.0.
_PSClasses_ include important features of object-oriented languages, 
like following: class inheritance, overriding methods,
calling overridden superclass methods, multiple constructors,
calling other constructors of same class,
calling superclass constructors.
The library also contains an uncommon feature: automatic generation 
of the constructor which accepts arguments corresponding to all 
instance variables. 
This feature resembles _case classes_ in Scala or _data classes_ 
in Kotlin. link:psClasses.html[Read more]

=== Reader monad: unary functions, Cats, implementation, example, alternatives

The article describes several ways of chaining unary functions 
most relevant for Reader monad and proceeds with a summary of Reader monad
functionality in _Cats_ library: it presents basic methods like __pure__,
__ask__, __map__, __andThen__, _local_ and __flatMap__. The _flatMap_
example is presented in several variants, both with and without a Reader.
The article then includes a simple implementation of __pure__, _map_ and 
_flatMap_ methods. A non-trivial, bigger example is converted from 
Haskell to Scala: Reader is employed here to avoid 
passing the same argument around. Several Scala alternatives are 
presented and compared to the Reader solution.
link:readerMonad.html[Read more]
